#---------------------------------------------------------------------------------------------------------
# !!! Uncomment this section in case of Data Plane is not deployed in same ns or cluster of Control Plane
#---------------------------------------------------------------------------------------------------------
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: kong-serviceaccount
#  namespace: kong
#---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: kong-proxy
  namespace: kong
spec:
  ports:
  - name: proxy
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: proxy-ssl
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: kong-dp
  type: LoadBalancer
---
#------------------------------------------------------------------------------
# Deployment: Kong Data Plane
#------------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: kong-proxy-status
  namespace: kong
spec:
  ports:
  - name: proxy-status
    port: 80
    protocol: TCP
    targetPort: 8100
  selector:
    app: kong-dp
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kong-dp
  name: kong-dp
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-dp
  template:
    metadata:
      annotations:
        kuma.io/gateway: enabled
        kuma.io/service-account-token-volume: kong-serviceaccount-token
        traffic.sidecar.istio.io/includeInboundPorts: ""
      labels:
        app: kong-dp
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: KONG_LICENSE_DATA
          valueFrom:
            secretKeyRef:
              key: license
              name: kong-enterprise-license
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_ROLE
          value: data_plane
        - name: KONG_CLUSTER_CERT
          value: /usr/local/kong/cluster_key/tls.crt
        - name: KONG_CLUSTER_CERT_KEY
          value: /usr/local/kong/cluster_key/tls.key
        - name: KONG_CLUSTER_CONTROL_PLANE
          value: kong-cluster-hybrid:8005
        - name: KONG_CLUSTER_TELEMETRY_ENDPOINT
          value: kong-cluster-hybrid:8006
        - name: KONG_PROXY_LISTEN
          value: 0.0.0.0:8000 reuseport backlog=16384, 0.0.0.0:8443 http2 ssl reuseport backlog=16384
        - name: KONG_STATUS_LISTEN
          value: 0.0.0.0:8100
        - name: KONG_PROXY_URL
          value: http://kong-proxy.client.net
        - name: KONG_ADMIN_API_URI
          value: http://kong-admin.client.net
        - name: KONG_ADMIN_GUI_URL
          value: http://kong-manager.client.net
        - name: KONG_PORTAL_GUI_HOST
          value: kong-devportal.client.net
        - name: KONG_PORTAL_API_URL
          value: http://kong-portal-api.client.net
        - name: KONG_PORTAL_GUI_PROTOCOL 
          value: http
        - name: KONG_NGINX_WORKER_PROCESSES
          value: "2"
        - name: KONG_PROXY_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ROUTER_FLAVOR
          value: traditional
        image: kong/kong-gateway:3.0.0.0-alpine
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "1"
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - kong quit
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 8100
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 8100
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: kong-dp
        ports:
        - containerPort: 8000
          name: proxy
          protocol: TCP
        - containerPort: 8443
          name: proxy-ssl
          protocol: TCP
        - containerPort: 8100
          name: metrics
          protocol: TCP
        volumeMounts:
        - name: cluster-key
          mountPath: "/usr/local/kong/cluster_key"
          readOnly: true
      volumes:
        - name: cluster-key
          secret:
            secretName: secret-hybrid-cluster-tls
            optional: false # default setting; "secret-tls" must exist

